In [1]:
import numpy as np

In [90]:
inputs = np.array([[0.5, -0.2, 0.1]])

In [92]:
targets = np.array([[0.4]])

In [97]:
for x,y in zip(inputs,targets):
    print (x,y)

[ 0.5 -0.2  0.1] [ 0.4]


In [101]:
x

array([ 0.5, -0.2,  0.1])

In [102]:
y

array([ 0.4])

In [103]:
weights_input_to_hidden = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])

In [104]:
weights_hidden_to_output = np.array([[0.3],
                       [-0.1]])

In [105]:
hidden_inputs=np.dot(x,weights_input_to_hidden)

In [106]:
hidden_inputs

array([-0.06, -0.18])

In [107]:
hidden_inputs.shape

(2,)

In [108]:
activation_function = lambda x : 1/(1 + np.exp(-x))

In [109]:
hidden_outputs = activation_function(hidden_inputs)

In [110]:
hidden_outputs

array([ 0.4850045 ,  0.45512111])

In [111]:
final_inputs = np.dot(hidden_outputs, weights_hidden_to_output)

In [112]:
final_inputs

array([ 0.09998924])

In [113]:
final_output = final_inputs

In [132]:
error = y-final_output

In [133]:
error 

array([ 0.30001076])

In [134]:
hidden_error = np.dot(weights_hidden_to_output,error)

In [135]:
hidden_error

array([ 0.09000323, -0.03000108])

In [136]:
hidden_error.shape

(2,)

In [137]:
hidden_error.shape

(2,)

In [138]:
otput_error_term = error*1

In [139]:
otput_error_term

array([ 0.30001076])

In [140]:
hidden_error.shape

(2,)

In [141]:
hidden_outputs.shape

(2,)

In [142]:
hidden_error_term = hidden_error*hidden_outputs*(1-hidden_outputs)

In [143]:
hidden_error_term

array([ 0.02248057, -0.00743984])

In [144]:
delta_weights_i_h = np.zeros(weights_input_to_hidden.shape)
delta_weights_h_o = np.zeros(weights_hidden_to_output.shape)

In [149]:
delta_weights_i_h += hidden_error_term * x[:,None]

In [150]:
delta_weights_i_h

array([[ 0.01124028, -0.00371992],
       [-0.00449611,  0.00148797],
       [ 0.00224806, -0.00074398]])

In [151]:
delta_weights_h_o += output_error_term*hidden_outputs[:,None]

In [152]:
delta_weights_h_o

array([[ 0.21484699],
       [ 0.20160927]])

In [ ]:
weights_input_to_hidden += 0.1*delta_weights_i_h/n_records
