In [1]:
import numpy as np

In [2]:
inputs = np.array([[0.5, -0.2, 0.1]])

In [3]:
inputs.shape

(1, 3)

In [5]:
weights_input_to_hidden = np.random.normal(0.0, 3**-0.5, 
                                       (3, 2))

In [16]:
weights_hidden_to_output = np.random.normal(0.0, 2**-0.5, 
                                       (2,1))

In [6]:
weights_input_to_hidden.shape

(3, 2)

In [12]:
hidden_inputs=np.dot(inputs,weights_input_to_hidden)

In [13]:
activation_function = lambda x : 1/(1 + np.exp(-x))

In [14]:
hidden_outputs = activation_function(hidden_inputs)

In [15]:
hidden_outputs

array([[ 0.52232758,  0.51508557]])

In [18]:
final_inputs = np.dot(hidden_outputs, weights_hidden_to_output)

In [19]:
final_inputs

array([[ 0.10671307]])

In [21]:
final_output = final_inputs

In [22]:
targets = np.array([[0.4]])

In [24]:
error = targets-final_output

In [25]:
error 

array([[ 0.29328693]])

In [26]:
output_error_term = error * 1.0